trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
- job: FirstJob
steps:
- bash: echo lets check
- bash: echo $(PipelineLevelVariable)
- job: SecondJob
steps:
- bash: echo Build SecondJob